#!/usr/bin/env node
// Build: concatenate src/css/*.css into themes/adwaita.css (in filename order,
// which is the cascade order the sheet needs), then bundle the settings plugin.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import * as esbuild from 'esbuild';

const root = new URL('.', import.meta.url).pathname;
const cssDir = join(root, 'src/css');

const parts = readdirSync(cssDir).filter(f => f.endsWith('.css')).sort();
const header = `/* Adwaita for Logseq — generated by build.mjs from src/css/. Do not edit. */\n`;
const css = header + parts.map(f => readFileSync(join(cssDir, f), 'utf8')).join('\n');

mkdirSync(join(root, 'themes'), { recursive: true });
writeFileSync(join(root, 'themes/adwaita.css'), css);
console.log(`themes/adwaita.css  ${parts.length} parts, ${css.split('\n').length} lines`);

await esbuild.build({
  entryPoints: [join(root, 'src/index.ts')],
  bundle: true,
  outfile: join(root, 'dist/index.js'),
  format: 'iife',
  target: 'chrome100',
  logLevel: 'info',
});
