#!/usr/bin/env node
// Build: concatenate src/css/*.css into themes/adwaita.css (in filename order,
// which is the cascade order the sheet needs), then bundle the settings plugin.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

export const root = new URL('.', import.meta.url).pathname;
const cssDir = join(root, 'src/css');

/**
 * Concatenate src/css/* in filename order — which is the cascade order the
 * sheet needs. Exported so the build-freshness test can rebuild in memory and
 * compare, instead of reimplementing this and drifting from it.
 */
export function buildCss() {
  const parts = readdirSync(cssDir).filter((f) => f.endsWith('.css')).sort();
  const header = `/* Adwaita for Logseq — generated by build.mjs from src/css/. Do not edit. */\n`;
  return { parts, css: header + parts.map((f) => readFileSync(join(cssDir, f), 'utf8')).join('\n') };
}

// Importing this module for buildCss() must not rebuild anything on disk, so
// only write when this file is the entry point.
const isEntryPoint =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isEntryPoint) {
  const { parts, css } = buildCss();
  mkdirSync(join(root, 'themes'), { recursive: true });
  writeFileSync(join(root, 'themes/adwaita.css'), css);
  console.log(`themes/adwaita.css  ${parts.length} parts, ${css.split('\n').length} lines`);

  await esbuild.build({
    entryPoints: [join(root, 'src/index.ts')],
    bundle: true,
    outfile: join(root, 'dist/index.js'),
    format: 'iife',
    target: 'chrome100',
    logLevel: 'info',
  });
}
