#!/usr/bin/env node
/**
 * Inline the vendored Adwaita icons (src/icons/*.svg) as CSS mask tokens.
 *
 *   node scripts/encode-icons.mjs
 *
 * Writes src/css/28-icons.css — one `--adw-icon-<name>` data URI per icon,
 * each the SVG file byte-for-byte (percent-encoded). Re-run after adding or
 * updating an icon; tests/static/headerbar.test.mjs fails if a token drifts
 * from its file, so the generated part cannot silently go stale.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const dir = join(root, 'src/icons');
const icons = readdirSync(dir).filter((f) => f.endsWith('.svg')).sort();

const lines = icons.map((f) => {
  const name = f.replace(/\.svg$/, '');
  const uri = encodeURIComponent(readFileSync(join(dir, f), 'utf8'));
  return `  --adw-icon-${name}: url("data:image/svg+xml,${uri}");`;
});

const css = `/* ==========================================================================
   Adwaita for Logseq — icons

   GENERATED by scripts/encode-icons.mjs from src/icons/ — do not edit.

   Adwaita's own symbolic icons (adwaita-icon-theme, LGPL-3.0-only OR
   CC-BY-SA-3.0; see src/icons/README.md), used as masks painted in
   currentColor, so they follow the text colour in light and dark exactly as
   GTK recolours symbolic icons.
   ========================================================================== */

:root {
${lines.join('\n')}
}
`;

writeFileSync(join(root, 'src/css/28-icons.css'), css);
console.log(`src/css/28-icons.css  ${icons.length} icons`);
